cmake_minimum_required(VERSION 3.20)
foreach(VAR RANGE 3)
    message(${VAR})
endforeach()

message("------------")
list(APPEND MYLIST a b c)
foreach(VAR IN LISTS MYLIST ITEMS d e)
    message(${VAR})
endforeach()

message(---------------------)
set(L1 one two three four)
set(L2 1 2 3 4)
foreach(num IN ZIP_LISTS L1 L2)
   message(word = ${num_0} ,num = ${num_1}) 
endforeach()
